name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Change this to the branch you want to analyze

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x  # Change this to your desired Go version

    - name: Build Go project
      run: go build

    - name: Run SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@v2.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
